import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar"; // Certifique-se de que o caminho está correto

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Real Estate App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar className="fixed top-0 left-0 w-full z-50" />
        {children}
      </body>
    </html>
  );
}
